# Generated by Django 3.1.5 on 2021-01-16 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_retailers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.IntegerField(default='', max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(default='', max_length=255)),
                ('message', models.TextField()),
            ],
        ),
    ]
